### ISSUE TITLE
Flag

### ISSUE THREAD

**Issue by Anonymnn** [b3nj5m1n/moderncardthemes#6]
First of all, I would like to thank you for your cards, they are great.
My problem is that I only get the German flag at the top no matter what I do (Note Type prettyWord).
Hope you can help me

**Comment by b3nj5m1n** [comment]
Hi, have you set the CountryISO and put a flag in your media directory with the filename `_flag_ISO.svg`?

If not, you can find country flags [here](https://github.com/lipis/flag-icons/tree/main/flags/4x3), for example. Download one of the files, rename to the appropriate filename, and either put it in your media folder manually, or to make sure there's no problems with syncing it, put it in a random empty card.

**Comment by Anonymnn** [comment]
Thank you
